name: 'Build Storybook'

env:
  NODE_OPTIONS: '--max-old-space-size=4096'

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.1.0
      - uses: ./.github/actions/pnpm-setup-action
      - name: Build docs
        run: pnpm nx run synapse-react-client:chromatic
