name: Deploy an sageaccountweb to dev

on:
  workflow_dispatch:
    inputs:
      tag:
        type: string
        description: Which tag to deploy from

jobs:
  build-and-deploy-sage-account-web:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch-or-tag }}
      - uses: ./.github/actions/pnpm-setup-action
        name: build
      - run: pnpm nx run ${{ inputs.app-name }}:build --mode=${{ inputs.vite-mode }}
      - name: upload-built-artifact
        uses: actions/upload-artifact@v4
        with:
          name: SageAccountWeb-dev-build
          path: apps/SageAccountWeb/build
          overwrite: true

